/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export interface CloseFacilityRequest {
    /** The `facility_id` of the facility to close */
    facilityId: PierApi.FacilityId;
}
