/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export interface CreateFacilityRequest {
    /** The `loan_agreement_id` of the loan agreement to create a facility for */
    loanAgreementId: PierApi.LoanAgreementId;
}
