/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreditStatus = "active" | "closed";

export const CreditStatus = {
    Active: "active",
    Closed: "closed",
} as const;
