/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export interface Facility {
    id: PierApi.FacilityId;
    /** The `application_id` of the corresponding loan application for the facility */
    applicationId: PierApi.ApplicationId;
    /** The `borrower_id` of the corresponding borrower the facility is for */
    borrowerId: PierApi.ConsumerBorrowerId;
    /** The `loan_agreement_id` of the corresponding loan agreement the facility is for */
    loanAgreementId: string;
    /** The type of credit production. */
    creditType: PierApi.CreditType;
    /** Timestamp the loan agreement object is created on */
    createdOn: Date;
    /** The status of the facility. */
    status: PierApi.CreditStatus;
    /** An object containing a summary of the terms of the facility. */
    terms: PierApi.LineOfCreditOffer;
}
