/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const CreateLoanAgreementRequest: core.serialization.ObjectSchema<
    serializers.CreateLoanAgreementRequest.Raw,
    PierApi.CreateLoanAgreementRequest
> = core.serialization.object({
    applicationId: core.serialization.property(
        "application_id",
        core.serialization.lazy(async () => (await import("../../..")).ApplicationId)
    ),
});

export declare namespace CreateLoanAgreementRequest {
    interface Raw {
        application_id: serializers.ApplicationId.Raw;
    }
}
