/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const LoanAgreementStatus: core.serialization.Schema<
    serializers.LoanAgreementStatus.Raw,
    PierApi.LoanAgreementStatus
> = core.serialization.enum_(["pending_signature", "signed", "expired"]);

export declare namespace LoanAgreementStatus {
    type Raw = "pending_signature" | "signed" | "expired";
}
