/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const LoanAgreement: core.serialization.ObjectSchema<serializers.LoanAgreement.Raw, PierApi.LoanAgreement> =
    core.serialization.object({
        id: core.serialization.lazy(async () => (await import("../../..")).LoanAgreementId),
        applicationId: core.serialization.property("application_id", core.serialization.string()),
        createdOn: core.serialization.property("created_on", core.serialization.string()),
        documentUrl: core.serialization.property("document_url", core.serialization.string()),
        signatureTimestamp: core.serialization.property("signature_timestamp", core.serialization.string().optional()),
        status: core.serialization.lazy(async () => (await import("../../..")).LoanAgreementStatus),
    });

export declare namespace LoanAgreement {
    interface Raw {
        id: serializers.LoanAgreementId.Raw;
        application_id: string;
        created_on: string;
        document_url: string;
        signature_timestamp?: string | null;
        status: serializers.LoanAgreementStatus.Raw;
    }
}
