/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const SignLoanAgreementResponse: core.serialization.ObjectSchema<
    serializers.SignLoanAgreementResponse.Raw,
    PierApi.SignLoanAgreementResponse
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("../../..")).LoanAgreementStatus),
    id: core.serialization.lazy(async () => (await import("../../..")).LoanAgreementId),
    applicationId: core.serialization.property(
        "application_id",
        core.serialization.lazy(async () => (await import("../../..")).ApplicationId)
    ),
    signatureTimestamp: core.serialization.property("signature_timestamp", core.serialization.date()),
    documentUrl: core.serialization.property("document_url", core.serialization.string()),
    createdOn: core.serialization.property("created_on", core.serialization.date()),
});

export declare namespace SignLoanAgreementResponse {
    interface Raw {
        status: serializers.LoanAgreementStatus.Raw;
        id: serializers.LoanAgreementId.Raw;
        application_id: serializers.ApplicationId.Raw;
        signature_timestamp: string;
        document_url: string;
        created_on: string;
    }
}
