/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export class BorrowerNotFoundError extends Error {
    readonly body: PierApi.BorrowerNotFound;

    constructor(body: PierApi.BorrowerNotFound) {
        super();
        Object.setPrototypeOf(this, BorrowerNotFoundError.prototype);
        this.body = body;
    }
}
