/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export class DocumentCannotBeSignedError extends Error {
    readonly body: PierApi.DocumentCannotBeSigned;

    constructor(body: PierApi.DocumentCannotBeSigned) {
        super();
        Object.setPrototypeOf(this, DocumentCannotBeSignedError.prototype);
        this.body = body;
    }
}
