/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export class DocumentCannotBeCreatedError extends Error {
    readonly body: PierApi.DocumentCannotBeCreated;

    constructor(body: PierApi.DocumentCannotBeCreated) {
        super();
        Object.setPrototypeOf(this, DocumentCannotBeCreatedError.prototype);
        this.body = body;
    }
}
