/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class DuplicateEinError extends Error {
    constructor() {
        super();
        Object.setPrototypeOf(this, DuplicateEinError.prototype);
    }
}
