/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export class DuplicateEinError extends Error {
    readonly body: PierApi.DuplicateEin;

    constructor(body: PierApi.DuplicateEin) {
        super();
        Object.setPrototypeOf(this, DuplicateEinError.prototype);
        this.body = body;
    }
}
