/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export class FacilityCannotBeCreatedError extends Error {
    readonly body: PierApi.FacilityCannotBeCreated;

    constructor(body: PierApi.FacilityCannotBeCreated) {
        super();
        Object.setPrototypeOf(this, FacilityCannotBeCreatedError.prototype);
        this.body = body;
    }
}
