/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export class FacilityAlreadyExistsError extends Error {
    readonly body: PierApi.FacilityAlreadyExists;

    constructor(body: PierApi.FacilityAlreadyExists) {
        super();
        Object.setPrototypeOf(this, FacilityAlreadyExistsError.prototype);
        this.body = body;
    }
}
