/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export class FacilityCannotBeClosedError extends Error {
    readonly body: PierApi.FacilityCannotBeClosed;

    constructor(body: PierApi.FacilityCannotBeClosed) {
        super();
        Object.setPrototypeOf(this, FacilityCannotBeClosedError.prototype);
        this.body = body;
    }
}
