/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class RateLimitError extends Error {
    constructor() {
        super();
        Object.setPrototypeOf(this, RateLimitError.prototype);
    }
}
