/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class ServerError extends Error {
    constructor() {
        super();
        Object.setPrototypeOf(this, ServerError.prototype);
    }
}
