/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const BeneficialOwnerId: core.serialization.Schema<
    serializers.BeneficialOwnerId.Raw,
    PierApi.BeneficialOwnerId
> = core.serialization.string();

export declare namespace BeneficialOwnerId {
    type Raw = string;
}
