/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const BeneficialOwners: core.serialization.ObjectSchema<
    serializers.BeneficialOwners.Raw,
    PierApi.BeneficialOwners
> = core.serialization.object({
    id: core.serialization.lazy(async () => (await import("../../..")).BeneficialOwnerId),
    address: core.serialization.lazyObject(async () => (await import("../../..")).Address),
    dateOfBirth: core.serialization.property("date_of_birth", core.serialization.string()),
    email: core.serialization.string(),
    firstName: core.serialization.property("first_name", core.serialization.string()),
    lastName: core.serialization.property("last_name", core.serialization.string()),
    phone: core.serialization.string(),
    percentOwnership: core.serialization.property("percent_ownership", core.serialization.number()),
    ssn: core.serialization.string(),
});

export declare namespace BeneficialOwners {
    interface Raw {
        id: serializers.BeneficialOwnerId.Raw;
        address: serializers.Address.Raw;
        date_of_birth: string;
        email: string;
        first_name: string;
        last_name: string;
        phone: string;
        percent_ownership: number;
        ssn: string;
    }
}
