/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const BusinessBorrowerId: core.serialization.Schema<
    serializers.BusinessBorrowerId.Raw,
    PierApi.BusinessBorrowerId
> = core.serialization.string();

export declare namespace BusinessBorrowerId {
    type Raw = string;
}
