/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const BusinessType: core.serialization.Schema<serializers.BusinessType.Raw, PierApi.BusinessType> =
    core.serialization.enum_(["corporation", "llc", "partnership", "sole_proprietorship"]);

export declare namespace BusinessType {
    type Raw = "corporation" | "llc" | "partnership" | "sole_proprietorship";
}
