/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const ConsumerBorrowerRequest: core.serialization.ObjectSchema<
    serializers.ConsumerBorrowerRequest.Raw,
    PierApi.ConsumerBorrowerRequest
> = core.serialization.object({
    address: core.serialization.lazyObject(async () => (await import("../../..")).Address),
    dateOfBirth: core.serialization.property("date_of_birth", core.serialization.string()),
    email: core.serialization.string(),
    firstName: core.serialization.property("first_name", core.serialization.string()),
    lastName: core.serialization.property("last_name", core.serialization.string()),
    kycCompletionDate: core.serialization.property("kyc_completion_date", core.serialization.string()),
    phone: core.serialization.string(),
    ssn: core.serialization.string(),
});

export declare namespace ConsumerBorrowerRequest {
    interface Raw {
        address: serializers.Address.Raw;
        date_of_birth: string;
        email: string;
        first_name: string;
        last_name: string;
        kyc_completion_date: string;
        phone: string;
        ssn: string;
    }
}
