/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const ConsumerBorrowerId: core.serialization.Schema<
    serializers.ConsumerBorrowerId.Raw,
    PierApi.ConsumerBorrowerId
> = core.serialization.string();

export declare namespace ConsumerBorrowerId {
    type Raw = string;
}
