/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const RejectionType: core.serialization.ObjectSchema<serializers.RejectionType.Raw, PierApi.RejectionType> =
    core.serialization.object({
        reason: core.serialization.string(),
        reasonMessage: core.serialization.property("reason_message", core.serialization.string()),
    });

export declare namespace RejectionType {
    interface Raw {
        reason: string;
        reason_message: string;
    }
}
