/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.facilities.create.Request.Raw,
    PierApi.CreateFacilityRequest
> = core.serialization.lazyObject(async () => (await import("../../..")).CreateFacilityRequest);

export declare namespace Request {
    type Raw = serializers.CreateFacilityRequest.Raw;
}

export const Response: core.serialization.Schema<serializers.facilities.create.Response.Raw, PierApi.Facility> =
    core.serialization.lazyObject(async () => (await import("../../..")).Facility);

export declare namespace Response {
    type Raw = serializers.Facility.Raw;
}
