/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export interface CreateLoanAgreementRequest {
    /** The `application_id` of the application to create the loan agreement for */
    applicationId: PierApi.ApplicationId;
}
