/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export interface LoanAgreement {
    id: PierApi.LoanAgreementId;
    /** The `application_id` of the corresponding loan application the agreement is for */
    applicationId: string;
    /** Timestamp the loan agreement object is created on */
    createdOn: string;
    /** Url where the loan agreement document is hosted */
    documentUrl: string;
    /** Timestamp of when e-signature is completed */
    signatureTimestamp: string;
    /** The status of the document */
    status: PierApi.LoanAgreementStatus;
}
