/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LoanAgreementStatus = "pending_signature" | "signed" | "expired";

export const LoanAgreementStatus = {
    PendingSignature: "pending_signature",
    Signed: "signed",
    Expired: "expired",
} as const;
