/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export interface SignLoanAgreementResponse {
    status: PierApi.LoanAgreementStatus;
    id: PierApi.LoanAgreementId;
    applicationId: PierApi.ApplicationId;
    signatureTimestamp: Date;
    documentUrl: string;
    createdOn: Date;
}
