/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BusinessContact {
    firstName: string;
    lastName: string;
    phone: string;
    email: string;
    title: string;
}
