/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BusinessType = "corporation" | "llc" | "partnership" | "sole_proprietorship";

export const BusinessType = {
    Corporation: "corporation",
    Llc: "llc",
    Partnership: "partnership",
    SoleProprietorship: "sole_proprietorship",
} as const;
