/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

/**
 * @example
 *     {
 *         address: {
 *             line1: "15 Main Street",
 *             line2: undefined,
 *             city: "Austin",
 *             state: "TX",
 *             zip: "73301"
 *         },
 *         id: "bor_a1d0c30d77104f35b4c842b99132624e",
 *         dateOfBirth: "1991-12-18",
 *         email: "jdough@acme.co",
 *         firstName: "Jane",
 *         lastName: "Dough",
 *         ssn: "999888777",
 *         kycCompletionDate: "2022-11-15",
 *         createdOn: new Date("2022-12-31T00:58:47.828Z"),
 *         phone: "2065886919"
 *     }
 */
export interface ConsumerBorrower {
    /** The address of the borrower */
    address: PierApi.Address;
    /** The borrower's date of birth (YYYY-MM-DD) */
    dateOfBirth: string;
    /** The ID of the borrower */
    id: PierApi.ConsumerBorrowerId;
    /** The borrower's valid email address */
    email: string;
    /** The borrower's first name */
    firstName: string;
    /** The borrower's last name */
    lastName: string;
    /** Date kyc completed on the borrower (YYYY-MM-DD) */
    kycCompletionDate: string;
    /** The borrower's 10-digit US phone number (e.g. 4152775050) */
    phone: string;
    /** 9-digit social security number of the borrower (e.g. 345543221) */
    ssn: string;
    /** The date the borrower was created */
    createdOn: Date;
}
