/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

/**
 * @example
 *     {
 *         id: "app_f0467657bba948e6a87292e182132848",
 *         borrowerId: "bor_a1d0c30d77104f35b4c842b99132624e",
 *         creditType: PierApi.CreditType.InstallmentLoan,
 *         status: PierApi.ApplicationStatus.Pending,
 *         createdOn: new Date("2022-12-31T01:36:52.606Z")
 *     }
 */
export interface Application {
    id?: PierApi.ApplicationId;
    /** The `borrower_id` of the borrower the application belongs to */
    borrowerId?: PierApi.ConsumerBorrowerId;
    /** The type of credit product. */
    creditType?: PierApi.CreditType;
    status?: PierApi.ApplicationStatus;
    /** Timestamp the application object is created on */
    createdOn?: Date;
    /** Timestamp when the application is either approved or rejected on */
    decisionedOn?: Date;
    /** If the application is approved, an object containing the credit offer details */
    offer?: PierApi.LoanOffer;
}
