/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

export interface ApproveApplicationRequest {
    offer: PierApi.LineOfCreditOffer;
    id: PierApi.ApplicationId;
    borrowerId: PierApi.ConsumerBorrowerId;
    creditType: PierApi.CreditType;
    status: PierApi.ApplicationStatus;
    createdOn: Date;
    decisionedOn: Date;
}
