/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         borrowerId: "bor_a1d0c30d77104f35b4c842b99132624e",
 *         creditType: "revolving_line_of_credit",
 *         requestedAmount: 200000
 *     }
 */
export interface CreateApplicationRequest {
    /** The `borrower_id` of the borrower the application is for */
    borrowerId: string;
    /** The type of credit product. */
    creditType: string;
    /** If the borrower requests an amount in their application, the requested loan or credit line amount (in cents). */
    requestedAmount?: number;
}
