/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreditType = "installment_loan" | "revolving_line_of_credit" | "closed_line_of_credit";

export const CreditType = {
    InstallmentLoan: "installment_loan",
    RevolvingLineOfCredit: "revolving_line_of_credit",
    ClosedLineOfCredit: "closed_line_of_credit",
} as const;
