/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetApplicationRequest {
    /** The id of the borrower you're requesting to retrieve */
    applicationId: string;
}
