/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LineOfCreditOffer {
    /** The amount (in cents) of the credit line offer (e.g. '200000' for $2,000.00) */
    amount: number;
    /** The apr (in basis points) of the credit line offer (e.g. '750' for 7.50%) */
    apr: number;
    /** The annual fee charged for the credit line (e.g. '5000' for $50.00) */
    annualFee: number;
    /**
     * The time in days between the last statement's closing date and the next statement's closing date.
     * For consumer lines of credit, the minimum is '21'
     *
     */
    billingCycle: number;
    /** If your platform charges a monthly finance charge for access to the line, the amount in cents */
    financeCharge?: number;
    /** The time in days between the end of a billing cycle and the bill's due date. For consumer lines of credit, the minimum is '21' */
    gracePeriod: number;
    /** The interest rate (in basis points) charged during the grace period. Must be '0' for consumer lines of credit. Defaults to `0` if omitted */
    gracePeriodInterestRate?: number;
    /** The interest rate (in basis points) of the loan or credit line offer (e.g. '750' for 7.50%) */
    interestRate: number;
    /** If you offer an introductory period with a reduced interest rate, the interest rate in basis points */
    introductoryOfferInterestRate?: number;
    /** If you offer an introductory period with a reduced interest rate, the term in months */
    introductoryOfferInterestRateTerm?: number;
    /** The fee charged if a borrower misses the payment due date, in cents (e.g. '2500' for $25.00) */
    latePaymentFee: number;
    /** The origination fee charged to originate the line in cents (e.g. '20000' for $200) */
    originationFee: number;
    /** The term of the line in months */
    term: number;
}
