/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LoanOffer {
    amount: number;
    annualFee: number;
    apr: number;
    financeCharge: number;
    gracePeriod: number;
    interestRate: number;
    originationFee: number;
    repaymentFrequency: string;
    latePaymentFee: number;
    term: number;
}
