/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PierApi } from "@fern-api/pier";

/**
 * @example
 *     PierApi.Offer.lineOfCredit({
 *         amount: 1000000,
 *         apr: 0,
 *         annualFee: 0,
 *         billingCycle: 30,
 *         financeCharge: 0,
 *         gracePeriod: 21,
 *         gracePeriodInterestRate: 0,
 *         interestRate: 0,
 *         latePaymentFee: 0,
 *         originationFee: 0,
 *         term: 24
 *     })
 *
 * @example
 *     PierApi.Offer.loan({
 *         amount: 1000000,
 *         annualFee: 0,
 *         apr: 0,
 *         financeCharge: 0,
 *         gracePeriod: 0,
 *         interestRate: 0,
 *         originationFee: 0,
 *         repaymentFrequency: "monthly",
 *         latePaymentFee: 0,
 *         term: 36
 *     })
 */
export type Offer = PierApi.Offer.LineOfCredit | PierApi.Offer.Loan | PierApi.Offer._Unknown;

export declare namespace Offer {
    interface LineOfCredit extends PierApi.LineOfCreditOffer, _Utils {
        type: "line_of_credit";
    }

    interface Loan extends PierApi.LoanOffer, _Utils {
        type: "loan";
    }

    interface _Unknown extends _Utils {
        type: void;
    }

    interface _Utils {
        _visit: <_Result>(visitor: PierApi.Offer._Visitor<_Result>) => _Result;
    }

    interface _Visitor<_Result> {
        lineOfCredit: (value: PierApi.LineOfCreditOffer) => _Result;
        loan: (value: PierApi.LoanOffer) => _Result;
        _other: (value: { type: string }) => _Result;
    }
}

export const Offer = {
    lineOfCredit: (value: PierApi.LineOfCreditOffer): PierApi.Offer.LineOfCredit => {
        return {
            ...value,
            type: "line_of_credit",
            _visit: function <_Result>(this: PierApi.Offer.LineOfCredit, visitor: PierApi.Offer._Visitor<_Result>) {
                return PierApi.Offer._visit(this, visitor);
            },
        };
    },

    loan: (value: PierApi.LoanOffer): PierApi.Offer.Loan => {
        return {
            ...value,
            type: "loan",
            _visit: function <_Result>(this: PierApi.Offer.Loan, visitor: PierApi.Offer._Visitor<_Result>) {
                return PierApi.Offer._visit(this, visitor);
            },
        };
    },

    _unknown: (value: { type: string }): PierApi.Offer._Unknown => {
        return {
            ...(value as any),
            _visit: function <_Result>(this: PierApi.Offer._Unknown, visitor: PierApi.Offer._Visitor<_Result>) {
                return PierApi.Offer._visit(this, visitor);
            },
        };
    },

    _visit: <_Result>(value: PierApi.Offer, visitor: PierApi.Offer._Visitor<_Result>): _Result => {
        switch (value.type) {
            case "line_of_credit":
                return visitor.lineOfCredit(value);
            case "loan":
                return visitor.loan(value);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
