/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RejectionReason =
    /**
     * Income does not meet requirement */
    | "income_too_low"
    /**
     * Bank account balance is too low */
    | "bank_balance_too_low"
    /**
     * Unable to predict regular pattern of income deposits */
    | "income_unpredictable"
    /**
     * Duplicate account (previously applied for a loan with a different email address) */
    | "user_account_duplicate"
    /**
     * State database lending restriction */
    | "sdb_check_failed"
    /**
     * Unable to link to a supported banking institution */
    | "bank_account_linking_error"
    /**
     * Under the Military Lending Act, loans to military personnel or their spouses
     * and dependents cannot be made if the interest and expenses associated with the
     * loan exceed an annual percentage rate (APR) of 36%. Due to these limits on
     * military-related lending, we can't lend to members of the military or their
     * spouses and dependents. Please feel free to contact us with any questions you
     * may have about this notice!
     *  */
    | "mla_failed"
    /**
     * Unable to verify identification documents */
    | "iddoc_failed"
    /**
     * No data from supported financial institution. Unsupported financial institution is linked */
    | "no_checking_or_savings_data"
    /**
     * Unable to pull enough bank history */
    | "insufficient_bank_history"
    /**
     * Unable to verify that your permanent residence is in a state */
    | "loan_location_no_license"
    /**
     * Unable to verify mailing address */
    | "address_invalid"
    /**
     * Unable to verify qualified income over a sustained period */
    | "income_verification_failed"
    /**
     * Recent deposits and withdrawals detected from other lenders */
    | "stacking_behavior"
    /**
     * Unable to verify SSN number */
    | "ssn_verification_failed"
    /**
     * Multiple Returned checks or Insufficient Fund Fees detected */
    | "too_many_nsfs"
    /**
     * Bank account has been flagged as potential fraud risk */
    | "fraud_risk_too_high"
    /**
     * Outstanding balance from previous loan */
    | "bankruptcy"
    /**
     * Payment processor is unable to authenticate user */
    | "processor_suspended"
    /**
     * Cash flow analysis - income funds are quickly depleted from bank account after income deposit */
    | "cash_flow_verification_failed";

export const RejectionReason = {
    IncomeTooLow: "income_too_low",
    BankBalanceTooLow: "bank_balance_too_low",
    IncomeUnpredictable: "income_unpredictable",
    UserAccountDuplicate: "user_account_duplicate",
    SdbCheckFailed: "sdb_check_failed",
    BankAccountLinkingError: "bank_account_linking_error",
    MlaFailed: "mla_failed",
    IddocFailed: "iddoc_failed",
    NoCheckingOrSavingsData: "no_checking_or_savings_data",
    InsufficientBankHistory: "insufficient_bank_history",
    LoanLocationNoLicense: "loan_location_no_license",
    AddressInvalid: "address_invalid",
    IncomeVerificationFailed: "income_verification_failed",
    StackingBehavior: "stacking_behavior",
    SsnVerificationFailed: "ssn_verification_failed",
    TooManyNsfs: "too_many_nsfs",
    FraudRiskTooHigh: "fraud_risk_too_high",
    Bankruptcy: "bankruptcy",
    ProcessorSuspended: "processor_suspended",
    CashFlowVerificationFailed: "cash_flow_verification_failed",
} as const;
