/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.loans.create.Request.Raw,
    PierApi.CreateLoanAgreementRequest
> = core.serialization.lazyObject(async () => (await import("../../..")).CreateLoanAgreementRequest);

export declare namespace Request {
    type Raw = serializers.CreateLoanAgreementRequest.Raw;
}

export const Response: core.serialization.Schema<serializers.loans.create.Response.Raw, PierApi.LoanAgreement> =
    core.serialization.lazyObject(async () => (await import("../../..")).LoanAgreement);

export declare namespace Response {
    type Raw = serializers.LoanAgreement.Raw;
}
