/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.loans.create.Request.Raw,
    PierApi.CreateLoanAgreementRequest
> = core.serialization.object({
    applicationId: core.serialization.property(
        "application_id",
        core.serialization.lazy(async () => (await import("../../..")).ApplicationId)
    ),
});

export declare namespace Request {
    interface Raw {
        application_id: serializers.ApplicationId.Raw;
    }
}

export const Response: core.serialization.Schema<serializers.loans.create.Response.Raw, PierApi.LoanAgreement> =
    core.serialization.lazyObject(async () => (await import("../../..")).LoanAgreement);

export declare namespace Response {
    type Raw = serializers.LoanAgreement.Raw;
}
