/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const ApplicationStatus: core.serialization.Schema<
    serializers.ApplicationStatus.Raw,
    PierApi.ApplicationStatus
> = core.serialization.enum_(["pending", "approved", "accepted", "rejected", "expired"]);

export declare namespace ApplicationStatus {
    type Raw = "pending" | "approved" | "accepted" | "rejected" | "expired";
}
