/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const LineOfCreditOffer: core.serialization.ObjectSchema<
    serializers.LineOfCreditOffer.Raw,
    PierApi.LineOfCreditOffer
> = core.serialization.object({
    amount: core.serialization.number(),
    apr: core.serialization.number(),
    annualFee: core.serialization.property("annual_fee", core.serialization.number()),
    billingCycle: core.serialization.property("billing_cycle", core.serialization.number()),
    financeCharge: core.serialization.property("finance_charge", core.serialization.number().optional()),
    gracePeriod: core.serialization.property("grace_period", core.serialization.number()),
    gracePeriodInterestRate: core.serialization.property(
        "grace_period_interest_rate",
        core.serialization.number().optional()
    ),
    interestRate: core.serialization.property("interest_rate", core.serialization.number()),
    introductoryOfferInterestRate: core.serialization.property(
        "introductory_offer_interest_rate",
        core.serialization.number().optional()
    ),
    introductoryOfferInterestRateTerm: core.serialization.property(
        "introductory_offer_interest_rate_term",
        core.serialization.number().optional()
    ),
    latePaymentFee: core.serialization.property("late_payment_fee", core.serialization.number()),
    originationFee: core.serialization.property("origination_fee", core.serialization.number()),
    term: core.serialization.number(),
});

export declare namespace LineOfCreditOffer {
    interface Raw {
        amount: number;
        apr: number;
        annual_fee: number;
        billing_cycle: number;
        finance_charge?: number | null;
        grace_period: number;
        grace_period_interest_rate?: number | null;
        interest_rate: number;
        introductory_offer_interest_rate?: number | null;
        introductory_offer_interest_rate_term?: number | null;
        late_payment_fee: number;
        origination_fee: number;
        term: number;
    }
}
