/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const LoanOffer: core.serialization.ObjectSchema<serializers.LoanOffer.Raw, PierApi.LoanOffer> =
    core.serialization.object({
        amount: core.serialization.number(),
        annualFee: core.serialization.property("annual_fee", core.serialization.number()),
        apr: core.serialization.number(),
        financeCharge: core.serialization.property("finance_charge", core.serialization.number()),
        gracePeriod: core.serialization.property("grace_period", core.serialization.number()),
        interestRate: core.serialization.property("interest_rate", core.serialization.number()),
        originationFee: core.serialization.property("origination_fee", core.serialization.number()),
        repaymentFrequency: core.serialization.property("repayment_frequency", core.serialization.string()),
        latePaymentFee: core.serialization.property("late_payment_fee", core.serialization.number()),
        term: core.serialization.number(),
    });

export declare namespace LoanOffer {
    interface Raw {
        amount: number;
        annual_fee: number;
        apr: number;
        finance_charge: number;
        grace_period: number;
        interest_rate: number;
        origination_fee: number;
        repayment_frequency: string;
        late_payment_fee: number;
        term: number;
    }
}
