/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const RejectionReason: core.serialization.Schema<serializers.RejectionReason.Raw, PierApi.RejectionReason> =
    core.serialization.enum_([
        "income_too_low",
        "bank_balance_too_low",
        "income_unpredictable",
        "user_account_duplicate",
        "sdb_check_failed",
        "bank_account_linking_error",
        "mla_failed",
        "iddoc_failed",
        "no_checking_or_savings_data",
        "insufficient_bank_history",
        "loan_location_no_license",
        "address_invalid",
        "income_verification_failed",
        "stacking_behavior",
        "ssn_verification_failed",
        "too_many_nsfs",
        "fraud_risk_too_high",
        "bankruptcy",
        "processor_suspended",
        "cash_flow_verification_failed",
    ]);

export declare namespace RejectionReason {
    type Raw =
        | "income_too_low"
        | "bank_balance_too_low"
        | "income_unpredictable"
        | "user_account_duplicate"
        | "sdb_check_failed"
        | "bank_account_linking_error"
        | "mla_failed"
        | "iddoc_failed"
        | "no_checking_or_savings_data"
        | "insufficient_bank_history"
        | "loan_location_no_license"
        | "address_invalid"
        | "income_verification_failed"
        | "stacking_behavior"
        | "ssn_verification_failed"
        | "too_many_nsfs"
        | "fraud_risk_too_high"
        | "bankruptcy"
        | "processor_suspended"
        | "cash_flow_verification_failed";
}
