/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const RejectRequest: core.serialization.ObjectSchema<serializers.RejectRequest.Raw, PierApi.RejectRequest> =
    core.serialization.object({
        rejectionReason: core.serialization.property(
            "rejection_reason",
            core.serialization.lazy(async () => (await import("../../..")).RejectionReason)
        ),
    });

export declare namespace RejectRequest {
    interface Raw {
        rejection_reason: serializers.RejectionReason.Raw;
    }
}
