/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const ApplicationNotFoundError: core.serialization.Schema<
    serializers.ApplicationNotFoundError.Raw,
    PierApi.ApplicationNotFound
> = core.serialization.lazyObject(async () => (await import("../../..")).ApplicationNotFound);

export declare namespace ApplicationNotFoundError {
    type Raw = serializers.ApplicationNotFound.Raw;
}
