/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const DocumentNotFoundError: core.serialization.Schema<
    serializers.DocumentNotFoundError.Raw,
    PierApi.DocumentNotFound
> = core.serialization.lazyObject(async () => (await import("../../..")).DocumentNotFound);

export declare namespace DocumentNotFoundError {
    type Raw = serializers.DocumentNotFound.Raw;
}
