/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const DocumentCannotBeCreatedError: core.serialization.Schema<
    serializers.DocumentCannotBeCreatedError.Raw,
    PierApi.DocumentCannotBeCreated
> = core.serialization.lazyObject(async () => (await import("../../..")).DocumentCannotBeCreated);

export declare namespace DocumentCannotBeCreatedError {
    type Raw = serializers.DocumentCannotBeCreated.Raw;
}
