/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const FacilityCannotBeCreatedError: core.serialization.Schema<
    serializers.FacilityCannotBeCreatedError.Raw,
    PierApi.FacilityCannotBeCreated
> = core.serialization.lazyObject(async () => (await import("../../..")).FacilityCannotBeCreated);

export declare namespace FacilityCannotBeCreatedError {
    type Raw = serializers.FacilityCannotBeCreated.Raw;
}
