/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const FacilityCannotBeClosedError: core.serialization.Schema<
    serializers.FacilityCannotBeClosedError.Raw,
    PierApi.FacilityCannotBeClosed
> = core.serialization.lazyObject(async () => (await import("../../..")).FacilityCannotBeClosed);

export declare namespace FacilityCannotBeClosedError {
    type Raw = serializers.FacilityCannotBeClosed.Raw;
}
