/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const InvalidInputError: core.serialization.Schema<serializers.InvalidInputError.Raw, PierApi.InvalidInput> =
    core.serialization.lazyObject(async () => (await import("../../..")).InvalidInput);

export declare namespace InvalidInputError {
    type Raw = serializers.InvalidInput.Raw;
}
