/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.applications.create.Request.Raw,
    PierApi.CreateApplicationRequest
> = core.serialization.lazyObject(async () => (await import("../../..")).CreateApplicationRequest);

export declare namespace Request {
    type Raw = serializers.CreateApplicationRequest.Raw;
}

export const Response: core.serialization.Schema<serializers.applications.create.Response.Raw, PierApi.Application> =
    core.serialization.lazyObject(async () => (await import("../../..")).Application);

export declare namespace Response {
    type Raw = serializers.Application.Raw;
}
