/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.applications.get.Response.Raw, PierApi.Application> =
    core.serialization.lazyObject(async () => (await import("../../..")).Application);

export declare namespace Response {
    type Raw = serializers.Application.Raw;
}
