/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<serializers.applications.reject.Request.Raw, PierApi.Reject> =
    core.serialization.object({
        rejectionReason: core.serialization.property(
            "rejection_reason",
            core.serialization.lazy(async () => (await import("../../..")).RejectionReason)
        ),
    });

export declare namespace Request {
    interface Raw {
        rejection_reason: serializers.RejectionReason.Raw;
    }
}

export const Response: core.serialization.Schema<serializers.applications.reject.Response.Raw, PierApi.Application> =
    core.serialization.lazyObject(async () => (await import("../../..")).Application);

export declare namespace Response {
    type Raw = serializers.Application.Raw;
}
