/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.borrowers.getAllBorrowers.Response.Raw,
    PierApi.ConsumerBorrower[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).ConsumerBorrower));

export declare namespace Response {
    type Raw = serializers.ConsumerBorrower.Raw[];
}
