/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.borrowers.listAllBorrowers.Response.Raw,
    PierApi.Borrower[]
> = core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).Borrower));

export declare namespace Response {
    type Raw = serializers.Borrower.Raw[];
}
