/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.borrowers.updateConsumerBorrower.Request.Raw,
    PierApi.ConsumerBorrowerRequest
> = core.serialization.lazyObject(async () => (await import("../../..")).ConsumerBorrowerRequest);

export declare namespace Request {
    type Raw = serializers.ConsumerBorrowerRequest.Raw;
}

export const Response: core.serialization.Schema<
    serializers.borrowers.updateConsumerBorrower.Response.Raw,
    PierApi.ConsumerBorrower
> = core.serialization.lazyObject(async () => (await import("../../..")).ConsumerBorrower);

export declare namespace Response {
    type Raw = serializers.ConsumerBorrower.Raw;
}
