/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const PierApiEnvironment = {
    Production: "https://production.pier-finance.com/api",
    Sandbox: "https://sandbox.pier-finance.com/api",
} as const;

export type PierApiEnvironment = typeof PierApiEnvironment.Production | typeof PierApiEnvironment.Sandbox;
