/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const CloseFacilityRequest: core.serialization.ObjectSchema<
    serializers.CloseFacilityRequest.Raw,
    PierApi.CloseFacilityRequest
> = core.serialization.object({
    facilityId: core.serialization.property(
        "facility_id",
        core.serialization.lazy(async () => (await import("../../..")).FacilityId)
    ),
});

export declare namespace CloseFacilityRequest {
    interface Raw {
        facility_id: serializers.FacilityId.Raw;
    }
}
