/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const CreateFacilityRequest: core.serialization.ObjectSchema<
    serializers.CreateFacilityRequest.Raw,
    PierApi.CreateFacilityRequest
> = core.serialization.object({
    loanAgreementId: core.serialization.property(
        "loan_agreement_id",
        core.serialization.lazy(async () => (await import("../../..")).LoanAgreementId)
    ),
});

export declare namespace CreateFacilityRequest {
    interface Raw {
        loan_agreement_id: serializers.LoanAgreementId.Raw;
    }
}
