/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const CreditStatus: core.serialization.Schema<serializers.CreditStatus.Raw, PierApi.CreditStatus> =
    core.serialization.enum_(["active", "closed"]);

export declare namespace CreditStatus {
    type Raw = "active" | "closed";
}
