/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const FacilityId: core.serialization.Schema<serializers.FacilityId.Raw, PierApi.FacilityId> =
    core.serialization.string();

export declare namespace FacilityId {
    type Raw = string;
}
