/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const Address: core.serialization.ObjectSchema<serializers.Address.Raw, PierApi.Address> =
    core.serialization.object({
        line1: core.serialization.property("line_1", core.serialization.string()),
        line2: core.serialization.property("line_2", core.serialization.string().optional()),
        city: core.serialization.string(),
        state: core.serialization.string(),
        zip: core.serialization.string(),
    });

export declare namespace Address {
    interface Raw {
        line_1: string;
        line_2?: string | null;
        city: string;
        state: string;
        zip: string;
    }
}
