/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const BaseErrorBody: core.serialization.ObjectSchema<serializers.BaseErrorBody.Raw, PierApi.BaseErrorBody> =
    core.serialization.object({
        errorType: core.serialization.property("error_type", core.serialization.string()),
        errorCode: core.serialization.property("error_code", core.serialization.string()),
        errorMessage: core.serialization.property("error_message", core.serialization.string()),
    });

export declare namespace BaseErrorBody {
    interface Raw {
        error_type: string;
        error_code: string;
        error_message: string;
    }
}
