/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const Id: core.serialization.Schema<serializers.Id.Raw, PierApi.Id> = core.serialization.string();

export declare namespace Id {
    type Raw = string;
}
