/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PierApi } from "@fern-api/pier";
import * as core from "../../../../core";

export const InvalidInput: core.serialization.ObjectSchema<serializers.InvalidInput.Raw, PierApi.InvalidInput> =
    core.serialization
        .object({
            errorDetail: core.serialization.property(
                "error_detail",
                core.serialization.list(
                    core.serialization.lazyObject(async () => (await import("../../..")).ErrorDetail)
                )
            ),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseErrorBody));

export declare namespace InvalidInput {
    interface Raw extends serializers.BaseErrorBody.Raw {
        error_detail: serializers.ErrorDetail.Raw[];
    }
}
